version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
  - package-ecosystem: docker
    directory: "/elixir/test/support/live_e2e_docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
  - package-ecosystem: npm
    directory: "/elixir/deps/phoenix"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
  - package-ecosystem: npm
    directory: "/elixir/deps/phoenix_html"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
  - package-ecosystem: npm
    directory: "/elixir/deps/phoenix_live_view"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
